// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHWz-INnabKqge-6hpUFPTTtoWlHIRwZY',
    appId: '1:919302558015:web:4dc65bf02be65a003e838a',
    messagingSenderId: '919302558015',
    projectId: 'watchmate-670df',
    authDomain: 'watchmate-670df.firebaseapp.com',
    storageBucket: 'watchmate-670df.firebasestorage.app',
    measurementId: 'G-RETBMQHCYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs0DIjq6s2Frvn-TUyGiKJr9pj0yP8rwM',
    appId: '1:919302558015:android:68dd89e72ca7d28e3e838a',
    messagingSenderId: '919302558015',
    projectId: 'watchmate-670df',
    storageBucket: 'watchmate-670df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYq8RwJozZVA1QzQIBIXjbvTZ_ML01ll0',
    appId: '1:919302558015:ios:8c1b61a565894ca83e838a',
    messagingSenderId: '919302558015',
    projectId: 'watchmate-670df',
    storageBucket: 'watchmate-670df.firebasestorage.app',
    iosBundleId: 'com.example.WatchMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYq8RwJozZVA1QzQIBIXjbvTZ_ML01ll0',
    appId: '1:919302558015:ios:8c1b61a565894ca83e838a',
    messagingSenderId: '919302558015',
    projectId: 'watchmate-670df',
    storageBucket: 'watchmate-670df.firebasestorage.app',
    iosBundleId: 'com.example.WatchMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHWz-INnabKqge-6hpUFPTTtoWlHIRwZY',
    appId: '1:919302558015:web:7c0f3c64f907ea543e838a',
    messagingSenderId: '919302558015',
    projectId: 'watchmate-670df',
    authDomain: 'watchmate-670df.firebaseapp.com',
    storageBucket: 'watchmate-670df.firebasestorage.app',
    measurementId: 'G-HGVDXEB01W',
  );
}
